Repository theforeman/foreman_maintain, pull requests merged in 2018-03, with the labels that each got.

#146 Add FreeBSD support to passenger-recycler
  bin/passenger-recycler
Labels: Needs testing, Not yet reviewed

#149 Add context into scenario
  lib/foreman_maintain.rb
  lib/foreman_maintain/context.rb
  lib/foreman_maintain/scenario.rb
  test/lib/cli/advanced_procedure_command_test.rb
  test/lib/context_test.rb
  test/lib/scenario_test.rb
  test/lib/support/definitions/procedures/with_param.rb
  test/lib/support/definitions/scenarios/with_context.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#154 Freeze rubocop version on 0.50.0
  .rubocop.yml
  Gemfile
  foreman_maintain-0.1.3.gem
  lib/foreman_maintain/upgrade_runner.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#156 Fixes #22851 - added new metadata 'advanced_run'
  lib/foreman_maintain.rb
  lib/foreman_maintain/cli/advanced/procedure/abstract_by_tag_command.rb
  lib/foreman_maintain/cli/advanced/procedure/by_tag_command.rb
  lib/foreman_maintain/cli/advanced/procedure/run_command.rb
  lib/foreman_maintain/concerns/metadata.rb
  test/lib/metadata_test.rb
  test/lib/support/definitions/procedures/advanced_run_not_allowed.rb
Labels: Needs testing, Not yet reviewed

#153 Fixes #22244 - Skip whitelisted steps
  lib/foreman_maintain/cli/base.rb
  lib/foreman_maintain/executable.rb
  lib/foreman_maintain/runner/execution.rb
  test/lib/reporter_test.rb
Labels: Needs testing, Not yet reviewed

#155 Fixes #22759 - enhance cpdb validate check
  config/foreman_maintain.yml.example
  config/foreman_maintain.yml.packaging
  definitions/checks/candlepin/validate_db.rb
  definitions/features/candlepin_database.rb
  definitions/procedures/candlepin/delete_orphaned_records_from_env_content.rb
  definitions/procedures/knowledge_base_article.rb
  lib/foreman_maintain/concerns/base_database.rb
  lib/foreman_maintain/concerns/system_helpers.rb
  lib/foreman_maintain/config.rb
Labels: Needs testing, Not yet reviewed

#158 Fixes #22762 - Check availability of repositories before upgrade (updated)
  definitions/checks/repositories/validate.rb
  definitions/features/downstream.rb
  definitions/scenarios/upgrade_to_satellite_6_2.rb
  definitions/scenarios/upgrade_to_satellite_6_2_z.rb
  definitions/scenarios/upgrade_to_satellite_6_3.rb
  definitions/scenarios/upgrade_to_satellite_6_3_z.rb
  lib/foreman_maintain/detector.rb
Labels: Needs testing, Waiting on contributor

#161 Fixes #22975 - satellite-installer requires LANG=en_US.utf-8
  definitions/procedures/installer/upgrade.rb
Labels: Needs testing, Not yet reviewed

#162 Fixes #22976, #22977 - foreman-installer doesnt take --upgrade
  definitions/procedures/installer/upgrade.rb
Labels: Needs testing, Not yet reviewed
