Repository theforeman/foreman_maintain, pull requests merged in 2018-04, with the labels that each got.

#159 Add installer feature
  definitions/features/installer.rb
  definitions/procedures/installer/upgrade.rb
  test/data/installer/capsule-installer/answers.capsule-installer.yaml
  test/data/installer/capsule-installer/capsule-installer.yaml
  test/data/installer/capsule-installer/config_header.txt
  test/data/installer/katello-installer/answers.capsule-certs-generate.yaml
  test/data/installer/katello-installer/answers.katello-installer.yaml
  test/data/installer/katello-installer/capsule-certs-generate.yaml
  test/data/installer/katello-installer/config_header.txt
  test/data/installer/katello-installer/katello-installer.yaml
  test/data/installer/simple_config/scenarios.d/foreman-answers.yaml
  test/data/installer/simple_config/scenarios.d/foreman.yaml
  test/data/installer/simple_config/scenarios.d/last_scenario.yaml
  test/definitions/features/installer_test.rb
  test/definitions/test_helper.rb
Labels: Needs testing, Waiting on contributor

#163 Fixes #23057 - fix mapping between procedure's option to param
  lib/foreman_maintain/cli/transform_clamp_options.rb
Labels: Needs testing

#151 Fixes #22458 - Add Katello service command
  definitions/checks/hammer_ping.rb
  definitions/checks/root_user.rb
  definitions/features/candlepin.rb
  definitions/features/downstream.rb
  definitions/features/foreman_proxy.rb
  definitions/features/foreman_server.rb
  definitions/features/foreman_tasks.rb
  definitions/features/katello.rb
  definitions/features/katello_service.rb
  definitions/features/pulp.rb
  definitions/features/puppet_server.rb
  definitions/features/service.rb
  definitions/procedures/katello_service/restart.rb
  definitions/procedures/katello_service/start.rb
  definitions/procedures/katello_service/stop.rb
  definitions/procedures/service/base.rb
  definitions/procedures/service/disable.rb
  definitions/procedures/service/enable.rb
  definitions/procedures/service/list.rb
  definitions/procedures/service/restart.rb
  definitions/procedures/service/start.rb
  definitions/procedures/service/status.rb
  definitions/procedures/service/stop.rb
  definitions/scenarios/services.rb
  definitions/scenarios/upgrade_to_satellite_6_2.rb
  definitions/scenarios/upgrade_to_satellite_6_2_z.rb
  definitions/scenarios/upgrade_to_satellite_6_3.rb
  definitions/scenarios/upgrade_to_satellite_6_3_z.rb
  lib/foreman_maintain/cli.rb
  lib/foreman_maintain/cli/base.rb
  lib/foreman_maintain/cli/service_command.rb
  lib/foreman_maintain/concerns/system_helpers.rb
  lib/foreman_maintain/feature.rb
  test/definitions/checks/hammer_ping_test.rb
  test/definitions/config/foreman_maintain.yml.test
  test/definitions/procedures/services_test.rb
  test/definitions/test_helper.rb
  test/lib/cli_test.rb
Labels: Needs testing, Not yet reviewed

#168 Fixes #23102 - hide foreman_tasks_fetch_tasks_status procedure
  definitions/procedures/foreman_tasks/fetch_tasks_status.rb
Labels: Needs testing, Not yet reviewed

#165 Fixes #22739, #21740 - Maintain hammer configuration
  .rubocop.yml
  README.md
  definitions/features/foreman_tasks.rb
  definitions/features/hammer.rb
  definitions/features/sync_plans.rb
  definitions/procedures/hammer_setup.rb
  lib/foreman_maintain.rb
  lib/foreman_maintain/cli/base.rb
  lib/foreman_maintain/concerns/hammer.rb
  lib/foreman_maintain/concerns/reporter.rb
  lib/foreman_maintain/error.rb
  lib/foreman_maintain/feature.rb
  lib/foreman_maintain/reporter.rb
  lib/foreman_maintain/utils.rb
  lib/foreman_maintain/utils/hammer.rb
  lib/foreman_maintain/utils/hash_tools.rb
  test/data/hammer/different_host_config/cli.modules.d/foreman.yml
  test/data/hammer/sample_admin_config/cli.modules.d/foreman.yml
  test/data/hammer/sample_default_config/cli.modules.d/foreman.yml
  test/data/hammer/sample_user_config/cli.modules.d/foreman.yml
  test/data/hammer/sample_user_config/cli_config.yml
  test/definitions/features/hammer_test.rb
  test/definitions/features/installer_test.rb
  test/definitions/procedures/hammer_setup_test.rb
  test/definitions/test_helper.rb
  test/lib/utils/hammer_test.rb
Labels: Needs re-review, Needs testing, Waiting on contributor

#170 Refs #23272 - add mongo 3.4 service name
  definitions/features/pulp.rb
Labels: Needs testing

#171 Fixes #23289 - Add note about puppetserver
  definitions/features/puppet_server.rb
Labels: Needs testing

#172 Fixes #23271 - use service-wait for service command
  definitions/features/service.rb
Labels: Needs testing

#129 Fixes #20156 - EPEL repo check
  definitions/checks/check_epel_repository.rb
Labels: Needs testing
