Repository theforeman/foreman_maintain, pull requests merged in 2018-06, with the labels that each got.

#185 Fixes #23685 - failure when curr_dir_path equals to settingsd_path
  definitions/procedures/remote_execution/remove_existing_settingsd.rb
Labels: Needs testing

#183 Fixes #23755 - remove hdparm and use only fio
  README.md
  definitions/checks/disk/performance.rb
  lib/foreman_maintain/utils/disk.rb
  lib/foreman_maintain/utils/disk/device.rb
  lib/foreman_maintain/utils/disk/io.rb
  lib/foreman_maintain/utils/disk/io/block_device.rb
  lib/foreman_maintain/utils/disk/io/file_system.rb
  lib/foreman_maintain/utils/disk/io_device.rb
  test/definitions/checks/disk_performance_test.rb
  test/lib/utils/disk/device_test.rb
  test/lib/utils/disk/io/block_device_test.rb
  test/lib/utils/disk/io_device_test.rb
Labels: Needs testing

#193 Fixes #23984 - Update PATH in initialization
  lib/foreman_maintain.rb
Labels: Needs testing, Not yet reviewed

#191 Fixes #23963 - enable beta tools repo for sat64
  definitions/features/downstream.rb
Labels: Needs testing, Not yet reviewed

#150 Fixes #22687 - Add openscap report check and procedure
  definitions/checks/foreman_openscap/invalid_report_associations.rb
  definitions/features/foreman_openscap.rb
  definitions/procedures/foreman_openscap/invalid_report_associations.rb
  test/definitions/checks/foreman_openscap/invalid_report_associations_test.rb
Labels: Needs re-review, Needs testing

#187 Fixes #23819 - upgrade guide for puppet if sat 6.3 & puppet3
  definitions/checks/puppet/provide_upgrade_guide.rb
  definitions/procedures/knowledge_base_article.rb
  definitions/scenarios/upgrade_to_satellite_6_4.rb
  definitions/scenarios/upgrade_to_satellite_6_4_z.rb
Labels: Needs testing

#195 Refs #23984 - resolved rubocop warning
  lib/foreman_maintain.rb
Labels: Needs testing, Not yet reviewed

#186 Fixes #23856 - on sat 6.3 & puppet4, enable puppet4 repo
  definitions/features/downstream.rb
  definitions/features/puppet_server.rb
Labels: Needs testing

#197 Fixes #24101 - execute confine for puppet3 check for sat 6.4
  definitions/scenarios/upgrade_to_satellite_6_4.rb
  definitions/scenarios/upgrade_to_satellite_6_4_z.rb
Labels: Needs testing
