Repository theforeman/foreman_maintain, pull requests merged in 2018-09, with the labels that each got.

#207 Fixes #24773 - corrected ansible repo to 2.6
  definitions/features/downstream.rb
Labels: Needs testing

#198 Fixes #23969 - clean contents of directory
  definitions/procedures/packages/update.rb
  lib/foreman_maintain/concerns/system_helpers.rb
Labels: Needs testing

#208 Fixes #24789 - Recognize services on capsule
  definitions/features/gofer.rb
  definitions/features/katello.rb
  definitions/features/pulp.rb
Labels: Needs testing

#209 Fixes #24797 - Use dynflowd on Foreman >= 1.17
  definitions/features/foreman_tasks.rb
  definitions/features/hammer.rb
Labels: Needs testing

#211 fixed minor typo in error message
  definitions/checks/backup/directory_ready.rb
Labels: Needs testing, Waiting on contributor

#214 Fixes #24942 - set UTF-8 explicitly
  bin/foreman-maintain
Labels: Needs testing

#210 Fixes #24793 - Add check for running services that does not rely on hammer
  definitions/checks/mongo/db_up.rb
  definitions/checks/services_up.rb
  definitions/features/candlepin.rb
  definitions/features/candlepin_database.rb
  definitions/features/foreman_database.rb
  definitions/features/foreman_proxy.rb
  definitions/features/foreman_server.rb
  definitions/features/foreman_tasks.rb
  definitions/features/gofer.rb
  definitions/features/katello.rb
  definitions/features/mongo.rb
  definitions/features/pulp.rb
  definitions/features/puppet_server.rb
  definitions/features/service.rb
  definitions/procedures/restore/mongo_dump.rb
  definitions/procedures/service/base.rb
  definitions/procedures/service/list.rb
  definitions/procedures/service/restart.rb
  lib/foreman_maintain.rb
  lib/foreman_maintain/concerns/system_helpers.rb
  lib/foreman_maintain/concerns/system_service.rb
  lib/foreman_maintain/feature.rb
  lib/foreman_maintain/utils.rb
  lib/foreman_maintain/utils/command_runner.rb
  lib/foreman_maintain/utils/service.rb
  lib/foreman_maintain/utils/service/abstract.rb
  lib/foreman_maintain/utils/service/remote_db.rb
  lib/foreman_maintain/utils/service/systemd.rb
  lib/foreman_maintain/utils/system_helpers.rb
  test/definitions/features/service_test.rb
  test/definitions/procedures/services_test.rb
  test/definitions/test_helper.rb
  test/lib/utils/service/remote_db_test.rb
  test/lib/utils/service/systemd_test.rb
  test/lib/utils/system_service_test.rb
Labels: Needs testing

#215 Fixes #24923 - Add check for duplicate puppet classes
  definitions/checks/foreman/puppet_class_duplicates.rb
  lib/foreman_maintain/concerns/system_helpers.rb
  test/definitions/checks/foreman/puppet_class_duplicates_test.rb
Labels: Needs testing, Not yet reviewed

#216 Fixes #24891 - return non-zero exit code when services are down
  definitions/features/service.rb
  lib/foreman_maintain/utils/service/abstract.rb
  test/definitions/features/installer_test.rb
  test/lib/utils/service/systemd_test.rb
Labels: Needs testing

#218 Fixes #24976 - modified IO threshold for disk speed check
  definitions/checks/disk/performance.rb
  test/definitions/checks/disk_performance_test.rb
Labels: Needs testing, Not yet reviewed

#224 Fixes #25019 - GA repositories enabled for 6.4
  definitions/features/downstream.rb
Labels: Needs testing, Not yet reviewed

#219 Fixes #24983 - set MAX_TERMINATION to 1
  config/passenger-recycler.yaml
Labels: Needs testing, Not yet reviewed

#213 Fixes #22229 - Check Available Disk Space
  definitions/checks/disk/available_space.rb
  lib/foreman_maintain/utils/disk/io_device.rb
Labels: Needs testing

#223 Fixes #25022 - skip repos validation if subscribed using act_key
  definitions/checks/repositories/validate.rb
  definitions/features/downstream.rb
Labels: Needs testing
