Repository theforeman/foreman_maintain, pull requests merged in 2019-07, with the labels that each got.

#270 Fixes #27122 - Sat 6.6.z scenario
  definitions/scenarios/upgrade_to_satellite_6_6_z.rb
Labels: Needs testing, Waiting on contributor

#272 Refs #27122 - add docker steps
  definitions/scenarios/upgrade_to_satellite_6_6_z.rb
Labels: Needs testing, Not yet reviewed

#275 Fixes #27291 - Make help tests whitespace insensitive
  test/lib/cli/advanced_procedure_command_test.rb
  test/lib/cli/health_command_test.rb
  test/lib/cli/maintenance_mode_command_test.rb
  test/lib/cli/packages_command_test.rb
  test/lib/cli/upgrade_command_test.rb
  test/lib/cli_test.rb
  test/test_helper.rb
Labels: Needs testing
