Repository theforeman/foreman_maintain, pull requests merged in 2019-05, with the labels that each got.

#257 Fixes #26502 - queries based on sync_plan changes in katello
  definitions/features/sync_plans.rb
  definitions/procedures/sync_plans/disable.rb
Labels: Needs testing

#260 Fixes #26725 - Add upgrade scenario for 6.6
  definitions/scenarios/upgrade_to_satellite_6_6.rb
Labels: Needs testing, Not yet reviewed

#249 Fixes #26216 - Lock package versions to protect against unwanted upgrades
  definitions/checks/version_locking_enabled.rb
  definitions/features/package_manager.rb
  definitions/procedures/packages/enable_version_locking.rb
  definitions/procedures/packages/lock_versions.rb
  definitions/procedures/packages/locking_status.rb
  definitions/procedures/packages/unlock_versions.rb
  definitions/procedures/packages/update.rb
  definitions/scenarios/upgrade_to_satellite_6_2.rb
  definitions/scenarios/upgrade_to_satellite_6_2_z.rb
  definitions/scenarios/upgrade_to_satellite_6_3.rb
  definitions/scenarios/upgrade_to_satellite_6_3_z.rb
  definitions/scenarios/upgrade_to_satellite_6_4.rb
  definitions/scenarios/upgrade_to_satellite_6_4_z.rb
  definitions/scenarios/upgrade_to_satellite_6_5.rb
  definitions/scenarios/upgrade_to_satellite_6_5_z.rb
  definitions/scenarios/upgrade_to_satellite_6_6.rb
  definitions/scenarios/version_locking.rb
  lib/foreman_maintain.rb
  lib/foreman_maintain/cli.rb
  lib/foreman_maintain/cli/base.rb
  lib/foreman_maintain/cli/packages_command.rb
  lib/foreman_maintain/concerns/system_helpers.rb
  lib/foreman_maintain/package_manager.rb
  lib/foreman_maintain/package_manager/base.rb
  lib/foreman_maintain/package_manager/dnf.rb
  lib/foreman_maintain/package_manager/yum.rb
  test/data/package_manager/yum/versionlock.conf.erb
  test/data/package_manager/yum/versionlock_locked.list
  test/data/package_manager/yum/versionlock_locked_alt.list
  test/data/package_manager/yum/versionlock_unlocked.list
  test/definitions/features/package_manager_test.rb
  test/definitions/procedures/hammer_setup_test.rb
  test/definitions/test_helper.rb
  test/lib/cli/packages_command_test.rb
  test/lib/cli_test.rb
  test/lib/package_manager/yum_test.rb
  test/lib/support/definitions/features/package_manager.rb
  test/lib/system_helpers_test.rb
Labels: Needs testing

#253 Fixes #26017 - treat tar packing response code 1 as success
  definitions/procedures/backup/config_files.rb
  definitions/scenarios/backup.rb
Labels: Needs testing

#244 Fixes #26050 - yum exclude list
  definitions/checks/yum_exclude.rb
Labels: Needs testing

#262 fix erros in README
  README.md
Labels: Needs testing, Waiting on contributor

#264 Fixes #26872 - Adds postgres config file to backup
  definitions/features/foreman_database.rb
Labels: Needs testing
