Repository theforeman/foreman_maintain, pull requests merged in 2020-06, with the labels that each got.

#339 Fixes #29713 - Display names of corrupted roles
  definitions/checks/foreman/check_corrupted_roles.rb
  test/definitions/checks/foreman/check_corrupted_roles_test.rb
Labels: Needs testing

#350 Bump version to 0.6.5
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#351 Fixes #30055 - Remove 6.7 capsule scenarios
  definitions/scenarios/upgrade_to_capsule_6_7.rb
  definitions/scenarios/upgrade_to_capsule_6_7_z.rb
Labels: Needs testing

#335 Fixes #29579 - added check for capsule package
  definitions/features/capsule.rb
Labels: 0.6.x, Needs testing

#354 Fix text in EPEL check
  definitions/checks/repositories/check_non_rh_repository.rb
Labels: Needs re-review, Needs testing, Waiting on contributor

#353 Fixes #25535 - changed the config_files definition
  definitions/features/foreman_server.rb
Labels: Needs testing

#362 Fixes #30208 - add yum to content switchover
  definitions/procedures/content/switchover.rb
Labels: Needs testing

#359 Fixes #30164 - Manage cron service in foreman-maintain restore
  definitions/scenarios/restore.rb
  lib/foreman_maintain/cli/restore_command.rb
Labels: Needs testing

#337 Fixes #29687 - Ignore the DHCP backup if external DHCP
  definitions/features/foreman_proxy.rb
Labels: Needs testing

#363 0.6.6 release
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
