Repository theforeman/foreman_maintain, pull requests merged in 2020-07, with the labels that each got.

#365 Fixes #30276 - handle nil case while updating all packages
  definitions/scenarios/packages.rb
Labels: 0.6.x, Needs testing

#361 Fixes #30204 - fix beta repositories
  lib/foreman_maintain/concerns/downstream.rb
Labels: 0.6.x, Needs testing

#367 Fixs #30324 - check for http(s) proxy
  definitions/checks/env_proxy.rb
Labels: Needs testing, Waiting on contributor

#369 Bump version to 0.6.7
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#368 Fixes #30342 - fix snapshot backup dir detection
  definitions/procedures/backup/snapshot/logical_volume_confirmation.rb
Labels: Needs testing

#370 Bump version to 0.6.8
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#373 remove extra inverted comma
  definitions/procedures/packages/locking_status.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#371 Fixes #30166 - fix key & handle nil in certs_tar
  definitions/features/foreman_proxy.rb
Labels: Needs testing

#357 Fixes #30024 - set home environment
  bin/foreman-maintain-complete
  lib/foreman_maintain.rb
Labels: Ready to merge

#377 Fixes #30469 - Use data_dir with tar transform option
  lib/foreman_maintain/concerns/base_database.rb
Labels: 0.6.x, Needs testing

#379 fixes #30501 - correct the check output
  definitions/checks/env_proxy.rb
Labels: 0.6.x, Needs testing, Not yet reviewed

#364 Fixes #30140 - Check should only run if dhcp provider is 'dhcp_isc'
  definitions/checks/foreman_proxy/verify_dhcp_config_syntax.rb
  definitions/features/foreman_proxy.rb
  test/definitions/checks/foreman_proxy/verify_dhcp_config_syntax_test.rb
Labels: Needs testing, Waiting on contributor

#376 Fixes #30458 - don't run steps inside content subcommands
  definitions/procedures/content/prepare.rb
  definitions/procedures/content/switchover.rb
  definitions/scenarios/content.rb
Labels: 0.6.x

#372 Fixes #30369 - Added condition to check .snar files
  definitions/procedures/backup/prepare_directory.rb
Labels: 0.6.x, Needs testing
