Repository theforeman/foreman_maintain, pull requests merged in 2020-12, with the labels that each got.

#421 Fixes #31327 - 6.9 sat and capsule scenarios
  definitions/procedures/content/migration_stats.rb
  definitions/procedures/content/prepare.rb
  definitions/procedures/content/prepare_abort.rb
  definitions/scenarios/content.rb
  definitions/scenarios/upgrade_to_capsule_6_9.rb
  definitions/scenarios/upgrade_to_capsule_6_9_z.rb
  definitions/scenarios/upgrade_to_satellite_6_9.rb
  definitions/scenarios/upgrade_to_satellite_6_9_z.rb
Labels: 6.9, Needs testing

#426 Fixes #31394 - use --reset-data or --reset with installer
  definitions/procedures/restore/installer_reset.rb
Labels: 6.9, Needs testing

#428 Bump version to 0.7.0
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#427 Fixes #31426 - use interactive for content prepare
  definitions/procedures/content/prepare.rb
Labels: Needs testing

#423 Fixes #31328 - fix online backup warning for include-db-dumps
  definitions/procedures/backup/online/safety_confirmation.rb
Labels: 6.9, Needs testing

#398 Fixes #30848 - Added feature foreman-cockpit
  definitions/features/foreman_cockpit.rb
Labels: 6.9, Needs testing

#394 Fixes #30809 - Adding the flag --occurrence=1 on the tar zxf command
  lib/foreman_maintain/utils/backup.rb
Labels: 6.9, Needs testing

#309 Fixes #28700 - flatten packages list before dnf action
  lib/foreman_maintain/package_manager/dnf.rb
Labels: 6.9, Needs testing

#429 Bump version to 0.7.1
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#430 Fixes #31512 - Implemented hammer workaround to resume tasks
  definitions/features/foreman_tasks.rb
Labels: 6.8, 6.9, Needs testing

#412 Fixes #31210 - add check for diskusage in cp-dir
  definitions/checks/disk/available_space_candlepin.rb
  definitions/features/candlepin.rb
  lib/foreman_maintain/utils/disk/io_device.rb
Labels: 6.8, 6.9, Needs testing

#433 Bump version to 0.7.2
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
