Repository theforeman/foreman_maintain, pull requests merged in 2020-11, with the labels that each got.

#411 Fixes #31172 - content prepare on sat 6.9 must handle pulpcore services
  definitions/features/pulpcore.rb
  definitions/procedures/content/prepare.rb
  definitions/scenarios/content.rb
Labels: Needs testing, Waiting on contributor

#413 Fixes #31246 - enable management of Pulpcore sockets
  definitions/features/pulpcore.rb
Labels: Needs testing, Waiting on contributor

#414 Fixes #31196 - add foreman-maintain content migration-stats
  definitions/procedures/content/migration_stats.rb
  definitions/scenarios/content.rb
  lib/foreman_maintain/cli/content_command.rb
Labels: Needs testing

#419 Fixes #31289 - Regenerate apipie cache after pulp3 content switchover
  definitions/scenarios/content.rb
Labels: Needs testing, Waiting on contributor

#418 Fixes #31283 - add foreman-maintain prep-6.10-upgrade command
  definitions/procedures/prep_6_10_upgrade.rb
  definitions/scenarios/prep_6_10_upgrade.rb
  lib/foreman_maintain/cli.rb
Labels: Needs testing

#420 Fixes #31305 - Block content switchover for downstream servers
  definitions/procedures/content/switchover.rb
  definitions/scenarios/content.rb
  lib/foreman_maintain/cli/content_command.rb
Labels: Needs testing

#416 Fixes #31264 - Add Github Actions support
  .github/workflows/ruby_tests.yml
  .travis.yml
  README.md
Labels: Needs testing

#415 Fixes #31253 - Validate if custom-hiera is yaml
  definitions/checks/foreman/check_checkpoint_segments.rb
Labels: 6.8, 6.9, Needs testing

#424 Fixes #31253 - Validate if custom-hiera is yaml (#415)
  definitions/checks/foreman/check_checkpoint_segments.rb
Labels: Needs testing, Not yet reviewed

#425 Bump version to 0.6.14
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
