Repository theforeman/foreman_maintain, pull requests merged in 2020-05, with the labels that each got.

#291 Fixes #28281 - no spinner on non-tty output
  lib/foreman_maintain/reporter/cli_reporter.rb
Labels: Needs testing

#321 Fixes #29246 - introduce new feature to handle foreman service
  definitions/features/apache.rb
  definitions/features/foreman_server.rb
  definitions/features/service.rb
  definitions/procedures/hammer_setup.rb
  definitions/procedures/service/stop.rb
  lib/foreman_maintain/utils/service/abstract.rb
  test/definitions/procedures/hammer_setup_test.rb
Labels: 0.6.x, Needs testing

#331 Fixes #29511 - do not run installer for f-m install/update
  definitions/scenarios/packages.rb
  lib/foreman_maintain.rb
Labels: 0.6.x, Needs testing

#316 Fixes #29002 - epel check before package install preparation step
  definitions/checks/check_epel_repository.rb
  definitions/checks/check_hotfix_installed.rb
  definitions/checks/disk/performance.rb
  definitions/checks/repositories/check_non_rh_repository.rb
  definitions/checks/repositories/check_upstream_repository.rb
  definitions/checks/repositories/validate.rb
Labels: 0.6.x, Needs testing

#348 Bump version to 0.6.4
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
