Repository theforeman/foreman_maintain, pull requests merged in 2020-04, with the labels that each got.

#329 Bump version to 0.6.3
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#330 update ruby versions in travis
  .travis.yml
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#333 Fixes #29577 - fix undefined method server_version in downstream
  lib/foreman_maintain/concerns/downstream.rb
Labels: 0.5.x, 0.6.x, Needs testing

#334 Fixed #29556 - correct method_name in feature dynflow_sidekiq
  definitions/features/dynflow_sidekiq.rb
Labels: Needs testing

#336 Fixes #29654 - hide disk performance check
  definitions/checks/disk/performance.rb
Labels: Needs testing
