Repository theforeman/foreman_maintain, pull requests merged in 2020-01, with the labels that each got.

#300 Adding content prepare procedure
  definitions/procedures/content/prepare.rb
Labels: Needs testing

#296 Fixes #28462 - Clean up qpid jrnl on restore
  definitions/procedures/restore/configs.rb
Labels: Needs testing, Not yet reviewed

#307 Fixes #28673 - Add SCL redis service name
  definitions/features/pulp3.rb
Labels: Needs testing

#308 Fixes #28500 - Pulp 3 backup/restore
  definitions/checks/pulpcore/db_up.rb
  definitions/features/foreman_database.rb
  definitions/features/instance.rb
  definitions/features/pulpcore.rb
  definitions/features/pulpcore_database.rb
  definitions/procedures/backup/offline/pulpcore_db.rb
  definitions/procedures/backup/online/pulpcore_db.rb
  definitions/procedures/backup/snapshot/logical_volume_confirmation.rb
  definitions/procedures/backup/snapshot/mount_pulpcore_db.rb
  definitions/procedures/content/prepare.rb
  definitions/procedures/pulpcore/migrate.rb
  definitions/procedures/restore/drop_databases.rb
  definitions/procedures/restore/pulpcore_dump.rb
  definitions/scenarios/backup.rb
  definitions/scenarios/restore.rb
  lib/foreman_maintain/concerns/base_database.rb
  lib/foreman_maintain/utils/backup.rb
  test/files/backups/katello_logical/pulpcore.dump
  test/files/backups/katello_online/pulpcore.dump
  test/lib/utils/backup_test.rb
Labels: Needs testing

#303 Fixes #28184 - add unlink option to fio to clean benchmark file
  lib/foreman_maintain/utils/disk/io_device.rb
Labels: 0.5.x, Needs testing, Not yet reviewed

#313 Fixes #28882: Update postgresql data location
  definitions/features/foreman_database.rb
  lib/foreman_maintain/concerns/base_database.rb
Labels: Needs testing
