Repository theforeman/foreman_maintain, pull requests merged in 2020-08, with the labels that each got.

#382 Fixes #30546 - python3 compatibility
  extras/foreman_protector/foreman-protector.py
Labels: 0.6.x, Needs testing

#380 Refs #30369 - Fix incremental_dir condition
  definitions/procedures/backup/prepare_directory.rb
Labels: 0.6.x, Needs testing

#383 Bump version to 0.6.9
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#386 Fixes #30640 - Fix tftp storage check
  definitions/checks/foreman_proxy/check_tftp_storage.rb
Labels: 0.6.x, Needs testing

#375 Fixes #29699 - Fix exit code for warning
  README.md
  lib/foreman_maintain/reporter/cli_reporter.rb
  lib/foreman_maintain/runner.rb
  lib/foreman_maintain/scenario.rb
  test/lib/runner_test.rb
Labels: 0.6.x, Needs testing

#387 Fixes #30649 - self-update for list-versions
  lib/foreman_maintain/cli/upgrade_command.rb
  test/lib/cli/upgrade_command_test.rb
Labels: 0.6.x, Needs testing, Not yet reviewed

#384 Fixes #30589 - make packages update & install commands consistent
  lib/foreman_maintain/cli/packages_command.rb
Labels: 0.6.x, Needs testing, Not yet reviewed

#388 Fixes #30652 - Fix upgrade procedure
  definitions/procedures/installer/upgrade.rb
Labels: 0.6.x, Needs testing
