Repository theforeman/foreman_maintain, pull requests merged in 2020-03, with the labels that each got.

#323 Bump version to 0.6.1
  lib/foreman_maintain/version.rb
Labels: Needs testing, Waiting on contributor

#324 Fixes #26017 - Exclude certain files for online backup
  definitions/features/katello.rb
  definitions/procedures/backup/config_files.rb
  definitions/scenarios/backup.rb
  lib/foreman_maintain/feature.rb
Labels: Needs testing

#326 Bump version to 0.5.3
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#327 Bump version to 0.6.2
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#320 Fixes #29227 - Add content commands to the top level
  README.md
  definitions/procedures/content/prepare.rb
  definitions/procedures/content/switchover.rb
  definitions/scenarios/content.rb
  lib/foreman_maintain/cli.rb
  lib/foreman_maintain/cli/content_command.rb
  test/lib/cli_test.rb
Labels: Needs testing
