Repository theforeman/foreman_maintain, pull requests merged in 2020-09, with the labels that each got.

#390 Fixes #30729 - Check checkpoint_segments tuning parameter
  definitions/checks/foreman/check_checkpoint_segments.rb
  definitions/features/installer.rb
  definitions/scenarios/upgrade_to_satellite_6_8.rb
Labels: 0.6.x, Needs testing

#381 Fixes #30527 - Add check for duplicate permissions
  definitions/checks/foreman/check_duplicate_permission.rb
  definitions/procedures/foreman/remove_duplicate_permissions.rb
Labels: 0.5.x, 0.6.x, Needs testing

#392 Fixes #30369 - incremental backup takes the full backup
  definitions/procedures/backup/prepare_directory.rb
Labels: Needs testing, Not yet reviewed

#393 Bump version to 0.5.5
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#395 Fixes #30810 - Print error to stderr
  lib/foreman_maintain/cli.rb
Labels: Needs testing

#396 Fixes #30810 - Print error to stderr
  lib/foreman_maintain/cli.rb
Labels: Needs testing, Not yet reviewed

#397 Bump version to 0.6.11
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#366 Fixes #30234 - validate yum.conf options as part of pre-upgrade
  definitions/checks/package_manager/yum/validate_yum_config.rb
  definitions/checks/yum_exclude.rb
Labels: Ready to merge

#258 Fixes #25853 - Improved suggestion to whitelist steps
  lib/foreman_maintain/reporter/cli_reporter.rb
  lib/foreman_maintain/scenario.rb
Labels: Needs re-review, Needs testing

#401 Fixes #30869 - Added yum-utils to allowlist
  extras/foreman_protector/foreman-protector.whitelist
Labels: Needs testing

#402 Fixes #30869 - Added yum-utils to allowlist
  extras/foreman_protector/foreman-protector.whitelist
Labels: Needs testing

#403 Bump version to 0.6.12
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#404 Fixes #30898 - add upgrade:run rake task
  definitions/procedures/installer/upgrade_rake_task.rb
  definitions/scenarios/upgrade_to_satellite_6_8.rb
  definitions/scenarios/upgrade_to_satellite_6_8_z.rb
Labels: Needs testing, Not yet reviewed

#405 Fixes #30898 - add upgrade:run rake task
  definitions/procedures/installer/upgrade_rake_task.rb
  definitions/scenarios/upgrade_to_satellite_6_8.rb
  definitions/scenarios/upgrade_to_satellite_6_8_z.rb
Labels: Needs testing, Not yet reviewed

#406 Bump version to 0.6.13
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#399 Fixes #30854 - Move downstream info into defs
  lib/foreman_maintain.rb
  lib/foreman_maintain/concerns/downstream.rb
Labels: Needs testing, Waiting on contributor
