Repository theforeman/foreman_maintain, pull requests merged in 2021-07, with the labels that each got.

#492 Bump version to 0.7.11
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#491 Bump version to 0.8.3
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#493 Fixes #32946 - use pulpcore_resource_manager if unit file is exist
  definitions/features/pulpcore.rb
  definitions/features/service.rb
Labels: Needs re-review, Needs testing, Waiting on contributor

#494 Fixes #25943 - Add support in spinner for plaintext output
  lib/foreman_maintain/cli/base.rb
  lib/foreman_maintain/reporter.rb
  lib/foreman_maintain/reporter/cli_reporter.rb
Labels: Needs re-review, Needs testing

#495 Bump version to 0.8.4
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#496 Refs #32946 - properly reference pulpcore_resource_manager_service
  definitions/features/pulpcore.rb
Labels: Needs testing

#497 Bump version to 0.8.5
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#498 Fixes #32944 - Fix typos in os detection
  lib/foreman_maintain/concerns/system_helpers.rb
Labels: Needs testing, Not yet reviewed

#500 Bump version to 0.8.6
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#484 Fixes #32818 - run pulp3 switchover as part of 6.10 upgrade
  definitions/procedures/content/prepare.rb
  definitions/procedures/content/switchover.rb
  definitions/procedures/pulp/print_remove_instructions.rb
  definitions/procedures/pulp/remove.rb
  definitions/scenarios/upgrade_to_satellite_6_10.rb
Labels: Needs testing

#355 Fixes #30120 - Added check-update option in foreman-maintain
  definitions/procedures/packages/check_update.rb
  definitions/scenarios/packages.rb
  lib/foreman_maintain/cli/packages_command.rb
  lib/foreman_maintain/package_manager/yum.rb
  test/lib/cli/packages_command_test.rb
  test/lib/package_manager/yum_test.rb
Labels: 6.10, Needs re-review, Needs testing

#501 Fixes #32319 - skip external databases while filtering services
  definitions/features/service.rb
Labels: Needs testing

#483 Fixes #32777 - remove pulp 2to3 migration plugin and tables
  definitions/procedures/pulp/remove.rb
  definitions/scenarios/content.rb
  lib/foreman_maintain/cli/content_command.rb
Labels: Needs testing, Waiting on contributor

#502 Bump version to 0.8.7
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#504 Refs #30323 - use SCL path for PostgreSQL config only on EL7
  definitions/features/foreman_database.rb
Labels: Needs testing

#503 Fixes #33053 - don't guard disable-system-checks by old katello
  definitions/procedures/restore/installer_reset.rb
Labels: Needs testing

#505 Refs #30094 - add assumeyes option for is-locked command
  lib/foreman_maintain/cli/packages_command.rb
Labels: Needs testing, Not yet reviewed

#506 Fixes #33145 - discover gofer feature only if service is enabled
  definitions/features/gofer.rb
Labels: Needs testing, Not yet reviewed

#345 Fixes #29818 - Fixed hammer setup_admin_access
  definitions/features/hammer.rb
  test/definitions/features/hammer_test.rb
Labels: 6.10, Needs re-review, Needs testing

#509 Bump version to 0.8.8
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#507 Fixes #33149 - use specific pulpcore worker names
  definitions/features/pulpcore.rb
Labels: Needs testing

#510 Fixes #33154 - stop services on content prepare abort
  definitions/scenarios/content.rb
Labels: Needs testing, Not yet reviewed

#511 Bump version to 0.8.9
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#512 Fixes #32945 - remove mod_wsgi and squid along with pulp2 packages
  definitions/procedures/pulp/remove.rb
Labels: Needs testing, Waiting on contributor
