Repository theforeman/foreman_maintain, pull requests merged in 2021-04, with the labels that each got.

#463 Fixes #32211 - Add qdpidd and qdrouterd to Katello services
  definitions/features/katello.rb
Labels: Needs testing

#466 Bump version to 0.8.0
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#467 Fixes #32292 - only collect .yml dynflow configs for services
  definitions/features/dynflow_sidekiq.rb
Labels: 6.9, Needs testing

#468 Fixes #32386 - Don't regenerate activemq queues on Capsule
  definitions/procedures/restore/regenerate_queues.rb
Labels: 6.8, 6.9

#450 Fixes #31951 - f-m online backup to skip /var/lib/pulp/cache
  definitions/features/pulp2.rb
  definitions/procedures/backup/pulp.rb
Labels: 6.10, Needs testing
