Repository theforeman/foreman_maintain, pull requests merged in 2021-06, with the labels that each got.

#476 Fixes #32672 - Add helpers for operating system's version facts
  lib/foreman_maintain/concerns/downstream.rb
  lib/foreman_maintain/concerns/system_helpers.rb
  lib/foreman_maintain/utils/facter.rb
Labels: Needs testing

#474 Fixes #30323 - Use pgsql scl data_dir only for EL7
  lib/foreman_maintain/concerns/base_database.rb
Labels: Needs testing

#478 Fixes #32736 - Use smart_proxy_dynflow_core upto Foreman 2.4
  definitions/features/foreman_proxy.rb
Labels: Needs testing

#480 Bump version to 0.7.10
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#479 Fixes #32737 - Skip disabled services from health check
  definitions/checks/services_up.rb
  definitions/features/service.rb
Labels: Needs testing, Not yet reviewed

#473 Fixes #32488 - use rpm to remove pulp2 packages
  definitions/procedures/pulp/remove.rb
Labels: Needs testing

#481 Refs #32424 - exclude ansible-runner packages from check
  definitions/checks/non_rh_packages.rb
Labels: Needs testing, Not yet reviewed

#485 Bump version to 0.8.2
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#487 Fixes #32909 - use keys.openpgp.org instead of dead sks-keyservers
  .github/workflows/ruby_tests.yml
Labels: Needs testing

#486 Fixes #32870 - refresh features after 6.10 upgrade
  definitions/procedures/refresh_features.rb
  definitions/scenarios/upgrade_to_satellite_6_10.rb
  lib/foreman_maintain.rb
Labels: 6.10, Needs testing

#488 Refs #32909 - don't install default ruby with rvm
  .github/workflows/ruby_tests.yml
Labels: Needs testing

#489 Refs #32870 - Add refresh features step in Capsule 6.10 upgrade
  definitions/scenarios/upgrade_to_capsule_6_10.rb
Labels: Needs testing, Not yet reviewed

#352 Fixes #30084 - Get control over interactive_option.
  lib/foreman_maintain/cli/base.rb
Labels: 6.10, Needs re-review, Needs testing

#490 Fixes #30094 - drop unwanted interactive options from packages cmd
  lib/foreman_maintain/cli/packages_command.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
