Repository theforeman/foreman_maintain, pull requests merged in 2021-08, with the labels that each got.

#514 Fixes #33185 - notify user prior to puppet content removal
  definitions/checks/puppet/warn_about_puppet_removal.rb
  definitions/scenarios/upgrade_to_satellite_6_10.rb
Labels: Needs testing

#499 Fixes #32996 - support removing old yum metadata files
  definitions/procedures/pulp/cleanup_old_metadata_files.rb
  definitions/scenarios/content.rb
  lib/foreman_maintain/cli/content_command.rb
Labels: Needs testing

#515 Bump version to 0.8.10
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#519 Fixes #33059 - allow restoring EL7 databases on EL8
  definitions/features/foreman_database.rb
  definitions/procedures/restore/extract_files.rb
  lib/foreman_maintain/concerns/base_database.rb
Labels: Needs testing

#475 Fixes #32633 - handle scl and nonscl package names dynamically
  .github/workflows/ruby_tests.yml
  definitions/checks/remote_execution/verify_settings_file_already_exists.rb
  definitions/features/foreman_cockpit.rb
  definitions/features/foreman_openscap.rb
  definitions/features/foreman_tasks.rb
  definitions/features/hammer.rb
  definitions/procedures/foreman_docker/remove_foreman_docker.rb
  lib/foreman_maintain/concerns/system_helpers.rb
Labels: Needs testing

#520 Refs #32633 - use foreman-proxy package for scl
  lib/foreman_maintain/concerns/system_helpers.rb
Labels: Needs testing

#518 Fixes #32634 - account for non-SCL redis services on el8
  definitions/features/pulpcore.rb
  definitions/features/redis.rb
Labels: Needs testing

#526 Fixes #33360 - use base database to get transform and config
  definitions/features/foreman_database.rb
  definitions/procedures/restore/extract_files.rb
  lib/foreman_maintain/concerns/base_database.rb
Labels: Needs testing

#524 Fixes #33355 - only include redis services if redis feature
  definitions/features/pulpcore.rb
Labels: Needs testing

#527 Fixes #33373 - dont call services method if feature not available
  definitions/features/instance.rb
Labels: Not yet reviewed, Needs testing
