Repository theforeman/foreman_maintain, pull requests merged in 2021-09, with the labels that each got.

#516 Fixes #33202 - add append-output mode to content prepare
  definitions/procedures/content/prepare.rb
  definitions/scenarios/content.rb
  lib/foreman_maintain/cli/content_command.rb
Labels: Needs re-review, Needs testing

#513 Fixes #33183 - adjusts the interactive command runner for nohup
  lib/foreman_maintain/utils/command_runner.rb
Labels: Needs testing

#528 Fixes #33384 - fix pulp dirs of snapshot backup
  definitions/procedures/backup/snapshot/logical_volume_confirmation.rb
  definitions/procedures/backup/snapshot/mount_pulp.rb
Labels: Not yet reviewed, Needs testing

#530 Fixes #33411 - disable and stop pulp3 services
  definitions/scenarios/upgrade_to_satellite_6_10.rb
Labels: Needs testing

#531 Refs #33346 - limit switchover run below Katello 4.0 version
  definitions/scenarios/upgrade_to_satellite_6_10.rb
Labels: Not yet reviewed, Needs testing

#533 Fixes #33437 - skip installer run after switchover
  definitions/procedures/content/switchover.rb
  definitions/scenarios/upgrade_to_satellite_6_10.rb
Labels: Needs testing

#534 Refs #33437 - refresh features after enable
  definitions/scenarios/upgrade_to_satellite_6_10.rb
Labels: Not yet reviewed, Needs testing

#529 Fixes #33406 - add latest z-stream check
  definitions/checks/check_for_newer_packages.rb
  definitions/scenarios/upgrade_to_satellite_6_10.rb
  lib/foreman_maintain/package_manager/yum.rb
Labels: Needs testing, 6.10, needs-cherrypick

#543 Fixes #33583 - dont add quotes while doing shellescape
  lib/foreman_maintain/concerns/system_helpers.rb
  test/lib/system_helpers_test.rb
Labels: Needs re-review, Needs testing, 6.10, needs-cherrypick

#539 Fixes #33603 - cleanup gemfile and gemspec from Ruby 1.8.7 remains
  Gemfile
  foreman_maintain.gemspec
Labels: Waiting on contributor, Needs testing

#538 Fixes #33528 - default to 'rubygem-' prefix for Ruby packages
  lib/foreman_maintain/concerns/system_helpers.rb
Labels: Needs testing

#535 Fixes #33488 - wipe journals for old (1.36) and new (1.39) qpidd
  definitions/procedures/restore/configs.rb
Labels: Needs testing

#541 Fixes #33568 - validate external db backup explicitly
  lib/foreman_maintain/utils/backup.rb
  test/files/backups/fpc_hybrid_pulp2_pulpcore_database_backup/config_files.tar.gz
  test/files/backups/fpc_hybrid_pulp2_pulpcore_database_backup/mongo_dump/.gitkeep
  test/files/backups/fpc_hybrid_pulp2_pulpcore_database_backup/pgsql_data.tar.gz
  test/files/backups/katello_hybrid_db_backup/candlepin.dump
  test/files/backups/katello_hybrid_db_backup/config_files.tar.gz
  test/files/backups/katello_hybrid_db_backup/foreman.dump
  test/files/backups/katello_hybrid_db_backup/pg_globals.dump
  test/files/backups/katello_hybrid_db_backup/pgsql_data.tar.gz
  test/lib/utils/backup_test.rb
Labels: Needs testing, 6.10, needs-cherrypick

#544 Fixes #33593 - only look for katello 3.18 package updates
  definitions/checks/check_for_newer_packages.rb
Labels: Needs testing
