Repository theforeman/foreman_maintain, pull requests merged in 2021-02, with the labels that each got.

#444 Fixes #31794 - allow migration scenarios on katello
  definitions/scenarios/content.rb
Labels: Needs testing

#445 0.7.5 release
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#442 Fixes #31617 - pulp remove procedure
  definitions/procedures/pulp/remove.rb
  definitions/scenarios/content.rb
  lib/foreman_maintain/cli/content_command.rb
Labels: Needs testing

#448 Fixes #31904 - Typo in foreman-maintain restore
  definitions/scenarios/restore.rb
Labels: Needs testing

#451 Fixes #31963 - check for number of commits in pull request
  .github/workflows/single_commit.yml
Labels: Needs testing, Not yet reviewed
