Repository theforeman/foreman_maintain, pull requests merged in 2021-01, with the labels that each got.

#434 Fixes #31575 - Online and offline backup with --include-db-dumps fails
  definitions/procedures/backup/online/safety_confirmation.rb
Labels: 6.9, Needs testing, Waiting on contributor

#431 Fixes #31520 - handle listing of systemd instantiated service
  definitions/features/dynflow_sidekiq.rb
  definitions/procedures/service/list.rb
  lib/foreman_maintain/utils/service/systemd.rb
Labels: 6.8, 6.9, Needs testing

#407 Fixes #30870 - Option to delete paused task.
  definitions/checks/foreman_tasks/not_paused.rb
  definitions/features/foreman_tasks.rb
  definitions/procedures/foreman_tasks/delete.rb
  definitions/procedures/foreman_tasks/resume.rb
  lib/foreman_maintain/reporter/cli_reporter.rb
  lib/foreman_maintain/runner.rb
  test/definitions/checks/foreman_tasks/not_paused_test.rb
  test/lib/reporter_test.rb
  test/lib/support/log_reporter.rb
Labels: 6.9, Needs re-review, Needs testing, On Hold

#436 Bump version to 0.7.3
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#435 Fixes #31592 - various pulp migration fixes
  definitions/features/pulpcore.rb
  definitions/procedures/prep_6_10_upgrade.rb
  definitions/scenarios/content.rb
  lib/foreman_maintain/cli.rb
Labels: Needs testing

#437 Refs #31328 - Context map include_db_dumps for SafetyConfirmation
  definitions/procedures/backup/online/safety_confirmation.rb
  definitions/scenarios/backup.rb
Labels: Needs testing, Not yet reviewed

#438 bump version to 0.7.4
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#439 Refs #31535 - Update check for satellite and capsule packages
  lib/foreman_maintain/cli/upgrade_command.rb
Labels: 6.9, Needs testing

#440 Bump version to 0.6.15
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
