Repository theforeman/foreman_maintain, pull requests merged in 2021-03, with the labels that each got.

#449 Fixes #31906 - Add content migration reset command
  definitions/procedures/content/migration_reset.rb
  definitions/scenarios/content.rb
  lib/foreman_maintain/cli/content_command.rb
Labels: 6.9, Needs testing

#446 Fixes #31680 - execute service actions in group
  definitions/features/service.rb
  definitions/procedures/service/base.rb
  definitions/procedures/service/list.rb
  test/definitions/features/service_test.rb
  test/definitions/procedures/services_test.rb
  test/definitions/test_helper.rb
Labels: 6.9, Needs testing

#447 Fixes #31886 - error out if psql and mongo packages missing
  definitions/checks/candlepin/db_up.rb
  definitions/checks/foreman/db_up.rb
  definitions/checks/mongo/db_up.rb
  definitions/features/mongo.rb
  lib/foreman_maintain/concerns/base_database.rb
Labels: 6.9, Needs testing, Not yet reviewed

#443 Fixes #31772 - Remove '--search' from hammer command.
  definitions/features/foreman_tasks.rb
Labels: 6.9, Needs testing, Not yet reviewed, Waiting on contributor

#452 Bump version to 0.7.6
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#453 Fixes #32033 - use mongo command instead of client.command
  definitions/features/mongo.rb
Labels: Needs testing

#454 Bump version to 0.7.7
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#455 Bump version to 0.6.16
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#457 Fixes #32059 - content migration-reset fails with undef error
  definitions/scenarios/content.rb
Labels: Needs testing

#458 Fixes #32104 - Use threads to run action on services
  definitions/features/service.rb
Labels: 6.9, Needs testing

#459 Bump version to 0.7.8
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#460 Fixes #32198 - Switchover needs to proxy yum and deb too
  definitions/procedures/content/switchover.rb
Labels: Needs testing

#456 Fixes #32052 - Dont run actions on disabled services
  definitions/features/service.rb
  definitions/procedures/service/base.rb
Labels: Needs testing

#461 Refs #32052 - fix signature of filter_services
  definitions/features/service.rb
Labels: Needs testing, Not yet reviewed

#462 Bump version to 0.7.9
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor
