Repository theforeman/foreman_maintain, pull requests merged in 2021-12, with the labels that each got.

#565 Fixes #34017 - add Satellite and Capsule 7.0, 7.0.z upgrade scenarios
  definitions/scenarios/upgrade_to_capsule_7_0.rb
  definitions/scenarios/upgrade_to_capsule_7_0_z.rb
  definitions/scenarios/upgrade_to_satellite_7_0.rb
  definitions/scenarios/upgrade_to_satellite_7_0_z.rb
Labels: Waiting on contributor, Not yet reviewed, Needs testing

#561 Fixes #33245 - use correct repo names on EL8
  lib/foreman_maintain/concerns/downstream.rb
  test/lib/concerns/downstream_test.rb
Labels: Needs testing

#567 Fixes #34039 - create check for pulp content's group ownership
  definitions/checks/pulpcore/group_ownership_check.rb
  definitions/scenarios/upgrade_to_satellite_6_10.rb
Labels: Needs testing, 6.9, 6.10, needs-cherrypick

#568 Fixes #34100 - don't fail on new token duration setting
  definitions/checks/foreman_proxy/check_tftp_storage.rb
Labels: Needs testing

#570 Fixes #34045 - adds a restart step after removing pulp2
  definitions/procedures/pulp/remove.rb
Labels: Needs testing

#571 Refs #33245 - also test for el7 sat maintenance 7.0 repos
  test/lib/concerns/downstream_test.rb
Labels: Needs testing

#569 Fixes #34101 - Drop locks and links when deleting tasks
  definitions/features/foreman_tasks.rb
Labels: Needs testing, 6.10, needs-cherrypick

#558 Fixes #33788 - introduce repos_manager and refactor code
  definitions/checks/repositories/check_non_rh_repository.rb
  definitions/checks/repositories/check_upstream_repository.rb
  definitions/features/system_repos.rb
  definitions/features/upstream_repositories.rb
  definitions/procedures/repositories/backup_enabled_repos.rb
  definitions/procedures/repositories/disable.rb
  definitions/procedures/repositories/enable.rb
  definitions/scenarios/self_upgrade.rb
  lib/foreman_maintain.rb
  lib/foreman_maintain/concerns/downstream.rb
  lib/foreman_maintain/concerns/system_helpers.rb
  lib/foreman_maintain/repository_manager.rb
  lib/foreman_maintain/repository_manager/el.rb
Labels: Needs re-review, Waiting on contributor, Needs testing, can_cherrypick, 7.0
