Repository theforeman/foreman_maintain, pull requests merged in 2021-11, with the labels that each got.

#554 Fixes #33828 - stop showing content prepare output twice
  definitions/procedures/content/prepare.rb
Labels: Needs testing

#553 Fixes #33281 - run installer with upgrade flags after restore
  definitions/procedures/installer/upgrade_rake_task.rb
  definitions/scenarios/restore.rb
Labels: Needs testing

#551 Fixes #33795 - suggest using f-maintain for z-stream update
  definitions/checks/check_for_newer_packages.rb
Labels: Needs re-review, Needs testing

#556 Add GenerateReportJob to list of excluded actions
  definitions/features/foreman_tasks.rb
Labels: Waiting on contributor, Needs testing

#550 Fixes #33734 - add db key for pulpcore backup
  definitions/features/pulpcore.rb
Labels: Needs testing

#557 Fixes #33908 - use pulpcore-manager instead of django-admin
  definitions/procedures/pulpcore/migrate.rb
Labels: Not yet reviewed, Needs testing

#555 Fixes #33829 - add disable Puppet command
  definitions/checks/foreman/check_puppet_capsules.rb
  definitions/procedures/puppet/remove_puppet.rb
  definitions/procedures/puppet/remove_puppet_data.rb
  definitions/scenarios/puppet.rb
  lib/foreman_maintain/cli.rb
  lib/foreman_maintain/cli/plugin_command.rb
  lib/foreman_maintain/concerns/system_helpers.rb
  test/data/puppet/foreman-answers-default.yaml
  test/data/puppet/foreman-answers-no-foreman-with-puppet.yaml
  test/data/puppet/foreman-proxy-content-with-puppet.yaml
  test/data/puppet/katello-answers-with-puppet.yaml
  test/definitions/procedures/puppet/remove_puppet_test.rb
  test/lib/cli/plugin_command_test.rb
  test/lib/cli_test.rb
  test/lib/support/definitions/checks/check_puppet_capsules.rb
  test/lib/support/definitions/scenarios/puppet.rb
Labels: Needs testing

#562 Refs #33829 - confine does not work to limit the execution
  definitions/scenarios/puppet.rb
Labels: Needs testing

#560 drop tomcat6 service name
  definitions/features/candlepin.rb
Labels: Waiting on contributor, Needs testing

#564 Fixes #33976 - run all checks before confirmation step
  definitions/scenarios/restore.rb
Labels: Needs testing

#559 Fixes #33272 - implement dry-run for restore
  definitions/scenarios/restore.rb
  lib/foreman_maintain/cli/restore_command.rb
  test/definitions/scenarios/restore_test.rb
  test/definitions/test_helper.rb
Labels: Needs testing

#546 Fixes #33620 - Command for upgrading foreman-maintain to major version
  definitions/features/system_repos.rb
  definitions/procedures/repositories/backup_enabled_repos.rb
  definitions/procedures/repositories/enable.rb
  definitions/scenarios/self_upgrade.rb
  lib/foreman_maintain/cli.rb
  lib/foreman_maintain/cli/self_upgrade_command.rb
  test/lib/cli_test.rb
Labels: Waiting on contributor, Needs testing
