Repository theforeman/foreman_maintain, pull requests merged in 2021-05, with the labels that each got.

#470 Refs #32491 - Various improvements to Pulp 3 migration prep
  definitions/procedures/prep_6_10_upgrade.rb
Labels: Needs testing

#471 Fixes #32554 - Add Satellite and Capsule 6.10 scenarios
  definitions/scenarios/upgrade_to_capsule_6_10.rb
  definitions/scenarios/upgrade_to_capsule_6_10_z.rb
  definitions/scenarios/upgrade_to_satellite_6_10.rb
  definitions/scenarios/upgrade_to_satellite_6_10_z.rb
Labels: Needs testing, Not yet reviewed

#469 Fixes #32424 - check for non Red Hat packages
  definitions/checks/non_rh_packages.rb
  lib/foreman_maintain/package_manager/yum.rb
Labels: 6.10, Needs testing, Not yet reviewed

#472 Bump version to 0.8.1
  lib/foreman_maintain/version.rb
Labels: Needs testing, Not yet reviewed, Waiting on contributor

#344 Fixes #29815 - Fixed the runner to execute rescue scenario
  lib/foreman_maintain/runner.rb
Labels: 6.10, 6.9, Needs testing, Not yet reviewed

#465 Fixes #32253 - Ensure PostgreSQL 12 has enough space for upgrade
  definitions/checks/disk/available_space_postgresql12.rb
  definitions/scenarios/upgrade_to_satellite_6_8.rb
  definitions/scenarios/upgrade_to_satellite_6_9.rb
  lib/foreman_maintain/utils/disk/io_device.rb
Labels: 6.8, 6.9, Needs testing, Not yet reviewed
