Repository theforeman/foreman_maintain, pull requests merged in 2022-06, with the labels that each got.

#576 Fixes #34195 - add apt package manager for debian
  definitions/scenarios/packages.rb
  lib/foreman_maintain/cli/packages_command.rb
  lib/foreman_maintain/concerns/system_helpers.rb
  lib/foreman_maintain/package_manager.rb
  lib/foreman_maintain/package_manager/apt.rb
  test/lib/foreman_maintain_test.rb
Labels: Waiting on contributor, Needs testing

#623 Fixes #35029 - Require Candlepin CA cert prior running installer
  definitions/procedures/installer/run_for_6_11.rb
  definitions/scenarios/upgrade_to_satellite_6_11.rb
Labels: Waiting on contributor, Needs testing, needs-cherrypick, 6.11

#627 drop passenger-recycler as we don't support passenger anymore
  bin/passenger-recycler
  config/passenger-recycler.yaml
  definitions/procedures/passenger_recycler.rb
  extras/passenger-recycler.cron
  foreman_maintain.gemspec
Labels: Waiting on contributor, Needs testing

#628 Fixes #35145 - strip out + and ~ from package versions
  lib/foreman_maintain/concerns/system_helpers.rb
  test/lib/concerns/system_helpers_test.rb
Labels: Needs testing
