Repository theforeman/foreman_maintain, pull requests merged in 2022-05, with the labels that each got.

#608 Fixes #34820 - nft rule to allow traffic from localhost
  definitions/features/nftables.rb
  lib/foreman_maintain/concerns/firewall/nftables_maintenance_mode.rb
Labels: Not yet reviewed, Needs testing, needs-cherrypick, 6.11

#611 Fixes #34874: foreman_cache_data should be a config file for backups …
  definitions/features/foreman_server.rb
  definitions/features/puppet_server.rb
Labels: Waiting on contributor, Needs testing, needs-cherrypick, 6.11

#612 Refs #34874: Include pulpcore_cache_data for installer in config_files
  definitions/features/foreman_server.rb
  definitions/features/installer.rb
  test/definitions/features/installer_test.rb
Labels: Waiting on contributor, Needs testing, needs-cherrypick, 6.11

#613 Fixes #34878 - enable Red Hat repositories to resolve dependencies if…
  definitions/scenarios/self_upgrade.rb
Labels: Waiting on contributor, Needs testing, 6.10, needs-cherrypick, 6.11

#610 Fixes #34854 - disable custom repo if it was not enabled
  definitions/scenarios/self_upgrade.rb
  test/definitions/scenarios/self_upgrade_test.rb
Labels: Needs testing, needs-cherrypick, 6.11

#617 Refs #34878 - don't enable RH repos when custom repo mentioned
  definitions/scenarios/self_upgrade.rb
Labels: Needs testing, 6.10, needs-cherrypick, 6.11

#618 Fixes #34928 - sanitize the repository label for EL7
  lib/foreman_maintain/repository_manager/el.rb
  test/lib/repository_manager/el_test.rb
Labels: Needs testing, needs-cherrypick, 6.11

#619 Fixes #34937 - Simplify self-upgrade mechanism
  definitions/procedures/packages/update.rb
  definitions/scenarios/self_upgrade.rb
  lib/foreman_maintain/cli/self_upgrade_command.rb
  lib/foreman_maintain/concerns/system_helpers.rb
  lib/foreman_maintain/package_manager/yum.rb
  test/definitions/scenarios/self_upgrade_test.rb
Labels: Needs testing, 6.10, needs-cherrypick, 6.11
