Repository theforeman/foreman_maintain, pull requests merged in 2022-04, with the labels that each got.

#604 Refs #33620 - unify maintenance repo var and param name
  definitions/scenarios/self_upgrade.rb
  lib/foreman_maintain/cli/self_upgrade_command.rb
Labels: Needs testing, 6.10, needs-cherrypick, 6.11

#602 Refs #33620 - limit target version upto N+1
  definitions/scenarios/self_upgrade.rb
  lib/foreman_maintain/cli/self_upgrade_command.rb
Labels: Needs testing, 6.10, needs-cherrypick, 6.11

#593 Fixes #34717 - The foreman-protector plugin for the dnf
  extras/foreman_protector/dnf/foreman-protector.py
  extras/foreman_protector/foreman-protector.whitelist
  extras/foreman_protector/yum/foreman-protector.py
Labels: Waiting on contributor, Needs testing

#606 Fixes #34761 - remove clean_requirements_on_remove from yum config check
  definitions/checks/package_manager/yum/validate_yum_config.rb
Labels: Waiting on contributor, Needs testing, needs-cherrypick, 6.11

#605 Refs #34717 - update Dnf PackageManager with respect to foreman-prote…
  definitions/checks/version_locking_enabled.rb
  definitions/procedures/packages/enable_version_locking.rb
  definitions/procedures/packages/lock_versions.rb
  definitions/procedures/packages/locking_status.rb
  definitions/procedures/packages/unlock_versions.rb
  lib/foreman_maintain/package_manager/base.rb
  lib/foreman_maintain/package_manager/dnf.rb
  lib/foreman_maintain/package_manager/yum.rb
  test/lib/package_manager/yum_test.rb
  test/test_helper.rb
Labels: Waiting on contributor, Needs testing

#607 Refs #34717 - remove unreferenced procedure to enable version locking
  definitions/procedures/packages/enable_version_locking.rb
Labels: Waiting on contributor, Needs testing, needs-cherrypick, 6.11

#609 Fixes #34821 - allow restoring miss-matched candlepin versions
  definitions/procedures/restore/candlepin_reset_migrations.rb
  definitions/scenarios/restore.rb
Labels: Needs testing, 6.10, needs-cherrypick, 6.11

#601 Fixes #34706 - introduce an option to exclude step from whitelist
  definitions/procedures/content/prepare.rb
  definitions/procedures/content/switchover.rb
  lib/foreman_maintain/concerns/metadata.rb
  lib/foreman_maintain/reporter/cli_reporter.rb
  test/lib/cli/health_command_test.rb
  test/lib/reporter_test.rb
  test/lib/support/definitions/checks/dummy.rb
  test/lib/support/definitions/scenarios/dummy_skip_whitelist.rb
Labels: Needs testing
