Repository theforeman/foreman_maintain, pull requests merged in 2022-08, with the labels that each got.

#634 Fixes #35261 - Run procedure FixPulpcoreArtifactOwnership during 6.11 upgrade
  definitions/scenarios/upgrade_to_capsule_6_11.rb
  definitions/scenarios/upgrade_to_capsule_6_11_z.rb
  definitions/scenarios/upgrade_to_satellite_6_11.rb
  definitions/scenarios/upgrade_to_satellite_6_11_z.rb
Labels: Waiting on contributor, Needs testing, needs-cherrypick, 6.11

#626 Fixes #35057 - the concern for upstream upgrades support
  definitions/checks/repositories/check_upstream_repository.rb
  definitions/features/instance.rb
  definitions/features/upstream.rb
  definitions/features/upstream_repositories.rb
  definitions/procedures/content/switchover.rb
  definitions/procedures/repositories/setup.rb
  foreman_maintain.gemspec
  lib/foreman_maintain.rb
  lib/foreman_maintain/concerns/os_facts.rb
  lib/foreman_maintain/concerns/upstream.rb
  test/lib/concerns/upstream_test.rb
Labels: Waiting on contributor, Needs testing

#636 Fixes #35404 - use current minor version for version bump
  definitions/scenarios/self_upgrade.rb
Labels: Needs testing

#635 Fixes #35252 - declare version map in separate file
  lib/foreman_maintain.rb
  lib/foreman_maintain/concerns/foreman_and_katello_version_map.rb
Labels: Waiting on contributor, Needs testing
