Repository theforeman/foreman_maintain, pull requests merged in 2022-02, with the labels that each got.

#575 Fixes #34197 - reuse find_installed_package instead of rpm_version
  definitions/features/capsule.rb
  definitions/features/katello.rb
  definitions/features/satellite.rb
  lib/foreman_maintain/concerns/system_helpers.rb
  lib/foreman_maintain/package_manager/yum.rb
  test/test_helper.rb
Labels: Waiting on contributor, Needs testing

#574 Fixes #34181 - add service restart after puppet removal
  definitions/scenarios/puppet.rb
Labels: Needs testing

#581 Fixes #34386 - don't validate the token in confine
  definitions/checks/foreman_proxy/check_tftp_storage.rb
Labels: Needs testing

#582 Fixes #34393 - use repoquery format that works on EL7 and EL8
  definitions/checks/check_hotfix_installed.rb
Labels: Needs testing

#583 Fixes #34403 - simplify hotfix check
  definitions/checks/check_hotfix_installed.rb
Labels: Needs testing

#584 Fixes #34405 - only use --disable-system-checks for Katello-like
  definitions/features/installer.rb
Labels: Needs testing

#585 Refs #34278 - run rake on Foreman only
  definitions/procedures/puppet/remove_puppet_data.rb
Labels: Not yet reviewed, Needs testing

#586 Fixes #34435 - update repoquery query format to support EL8
  definitions/checks/check_hotfix_installed.rb
Labels: Needs re-review, Needs testing
