Repository theforeman/foreman_maintain, pull requests merged in 2022-09, with the labels that each got.

#638 Fixes #35479 - use ForemanAndKatelloVersionMap concern
  lib/foreman_maintain.rb
  lib/foreman_maintain/concerns/upstream.rb
  test/lib/concerns/upstream_test.rb
  test/lib/foreman_maintain_test.rb
Labels: Needs testing

#640 Refs #34878 - don't enable RH repos when custom repo mentioned
  definitions/scenarios/self_upgrade.rb
Labels: Needs testing

#643 Fixes #35533 - remove duplicate ssl params of cpdb cmd
  definitions/features/candlepin_database.rb
  test/definitions/features/candlepin_database_test.rb
  test/support/candlepin_with_ssl.conf
  test/support/candlepin_without_ssl.conf
Labels: Waiting on contributor, needs-cherrypick, 6.11, 6.12

#644 Fixes #35544 - Remove ansible-runner from non-RH package exception list
  definitions/checks/non_rh_packages.rb
Labels: Needs re-review, Waiting on contributor

#639 Fixes #35487 - add missing psql and nftables dependencies
  extras/foreman_protector/foreman-protector.whitelist
Labels: Needs testing, 6.10, needs-cherrypick, 6.11, 6.12

#645 Fixes #35404 - use current minor version for version bump
  definitions/scenarios/self_upgrade.rb
Labels: Not yet reviewed
