Repository theforeman/foreman_maintain, pull requests merged in 2022-01, with the labels that each got.

#577 Fixes #34231 - Fix to check pulp group ownership to "/var/lib/pulp/content"
  definitions/checks/pulpcore/group_ownership_check.rb
Labels: Waiting on contributor, Needs testing

#578 Fixes #34278 - only stop services if available
  definitions/procedures/puppet/remove_puppet.rb
Labels: Needs testing

#579 Fixes #34281 - pass array to rhsm_disable_repos
  definitions/procedures/repositories/disable.rb
  definitions/procedures/repositories/enable.rb
  lib/foreman_maintain/concerns/downstream.rb
Labels: Not yet reviewed, Needs testing
