Repository theforeman/foreman_maintain, pull requests merged in 2022-03, with the labels that each got.

#590 Refs #33620 - update messages in self-upgrade scenario
  definitions/scenarios/self_upgrade.rb
  lib/foreman_maintain/cli/self_upgrade_command.rb
Labels: Not yet reviewed, Needs testing, 6.10, needs-cherrypick, 7.0

#588 Fixes #33620 - Command for upgrading foreman-maintain to major version
  definitions/features/system_repos.rb
  definitions/procedures/repositories/backup_enabled_repos.rb
  definitions/procedures/repositories/enable.rb
  definitions/scenarios/self_upgrade.rb
  lib/foreman_maintain/cli.rb
  lib/foreman_maintain/cli/self_upgrade_command.rb
  test/lib/cli_test.rb
Labels: Waiting on contributor, Not yet reviewed, Needs testing

#573 drop support for service-wait
  lib/foreman_maintain/utils/service/systemd.rb
  test/lib/utils/service/systemd_test.rb
Labels: Waiting on contributor, Needs testing

#589 Fixes #34463 - remove pulp2 automatically on upgrade to 7.0
  definitions/scenarios/upgrade_to_satellite_7_0.rb
Labels: Needs testing, needs-cherrypick, 7.0

#594 Fixes #34618 - clean /etc/pki/pulp/content when removing pulp2
  definitions/procedures/pulp/remove.rb
Labels: Needs testing, needs-cherrypick, 7.0

#595 Refs #34463 - remove pulp2 automatically on capsule upgrade to 7.0
  definitions/scenarios/upgrade_to_capsule_7_0.rb
Labels: Waiting on contributor, Needs testing

#599 Refs #34685 - modify upgrade scenarios for 6.11 version
  definitions/scenarios/upgrade_to_capsule_6_11.rb
  definitions/scenarios/upgrade_to_capsule_6_11_z.rb
  definitions/scenarios/upgrade_to_satellite_6_11.rb
  definitions/scenarios/upgrade_to_satellite_6_11_z.rb
Labels: Needs testing, 6.10, needs-cherrypick, 7.0

#597 Refs #34685 - modify repository versions to 6.11
  lib/foreman_maintain/concerns/downstream.rb
  test/lib/concerns/downstream_test.rb
Labels: Needs testing, 6.10, needs-cherrypick, 7.0

#598 Refs #34685 - modify version to 6.11 in self upgrade example
  lib/foreman_maintain/cli/self_upgrade_command.rb
Labels: Needs testing, 6.10, needs-cherrypick, 7.0

#596 Fixes #34631 - add command & procedure to update pulpcore artifact ownership
  definitions/procedures/content/fix_pulpcore_artifact_permissions.rb
  definitions/scenarios/content.rb
  lib/foreman_maintain/cli/content_command.rb
Labels: Waiting on contributor, Needs testing

#600 Fixes #34699 - don't try to delete pulp mountpoints
  definitions/procedures/pulp/remove.rb
Labels: Needs testing, 6.10, needs-cherrypick
