Repository theforeman/foreman_maintain, pull requests merged in 2023-03, with the labels that each got.

#691 Fixes #36152 - don't try to backup or restore pg_globals
  definitions/procedures/backup/online/pg_global_objects.rb
  definitions/procedures/restore/pg_global_objects.rb
  definitions/scenarios/backup.rb
  definitions/scenarios/restore.rb
  lib/foreman_maintain/concerns/base_database.rb
  lib/foreman_maintain/utils/backup.rb
Labels: Needs re-review

#690 Add enabling satellite-maintenance if present
  definitions/scenarios/self_upgrade.rb
  lib/foreman_maintain.rb
  lib/foreman_maintain/package_manager/dnf.rb
  test/lib/cli/upgrade_command_test.rb
  test/lib/foreman_maintain_test.rb
  test/lib/package_manager/dnf_test.rb
  test/test_helper.rb
Labels: Waiting on contributor

#693 Add 6.14 upgrade scenario
  definitions/scenarios/upgrade_to_capsule_6_14.rb
  definitions/scenarios/upgrade_to_capsule_6_14_z.rb
  definitions/scenarios/upgrade_to_satellite_6_14.rb
  definitions/scenarios/upgrade_to_satellite_6_14_z.rb
Labels: Needs re-review, Waiting on contributor

#694 Release 1.2.7
  lib/foreman_maintain/version.rb
Labels: Waiting on contributor

#695 use correct package name on Debian systems
  definitions/scenarios/self_upgrade.rb
  lib/foreman_maintain.rb
  test/lib/cli/upgrade_command_test.rb
  test/lib/foreman_maintain_test.rb
Labels: Waiting on contributor

#698 check for systemd by looking at /run/systemd/system
  lib/foreman_maintain/concerns/system_helpers.rb
Labels: Needs re-review, Waiting on contributor

#696 add an advanced command to list detected features
  definitions/procedures/foreman_maintain_features.rb
  test/definitions/procedures/foreman_maintain_features_test.rb
Labels: Waiting on contributor

#702 Fixes #36230 - Puppet removal parameter to installer is no longer used
  definitions/procedures/puppet/remove_puppet.rb
  test/definitions/procedures/puppet/remove_puppet_test.rb
Labels: Waiting on contributor

#710 always add Rubocop tasks
  Rakefile
Labels: Waiting on contributor

#709 Add release workflow
  .github/workflows/release.yml
Labels: Waiting on contributor

#708 Add Ruby 3.1 and 3.2 to testing
  .github/workflows/ruby_tests.yml
Labels: Waiting on contributor

#701 add check whether postgres user can read dump files
  definitions/checks/restore/validate_postgresql_dump_permissions.rb
  definitions/scenarios/restore.rb
  test/definitions/checks/restore/validate_postgresql_dump_permissions_test.rb
Labels: Needs re-review, Waiting on contributor
