Repository theforeman/foreman_maintain, pull requests merged in 2023-09, with the labels that each got.

#732 Convert all code to use DNF
  definitions/checks/check_hotfix_installed.rb
  definitions/checks/package_manager/dnf/validate_dnf_config.rb
  definitions/checks/repositories/check_upstream_repository.rb
  definitions/procedures/packages/installer_confirmation.rb
  definitions/procedures/packages/update.rb
  definitions/scenarios/self_upgrade.rb
  definitions/scenarios/upgrade_to_capsule_6_15.rb
  definitions/scenarios/upgrade_to_capsule_6_15_z.rb
  definitions/scenarios/upgrade_to_katello_nightly.rb
  definitions/scenarios/upgrade_to_satellite_6_15.rb
  definitions/scenarios/upgrade_to_satellite_6_15_z.rb
  extras/foreman_protector/foreman-protector.conf
  extras/foreman_protector/yum/foreman-protector.py
  lib/foreman_maintain/concerns/system_helpers.rb
  lib/foreman_maintain/package_manager.rb
  lib/foreman_maintain/package_manager/dnf.rb
  lib/foreman_maintain/package_manager/yum.rb
  lib/foreman_maintain/repository_manager/el.rb
  test/data/package_manager/dnf/foreman-protector.conf.erb
  test/definitions/procedures/update_package_test.rb
  test/lib/package_manager/dnf_test.rb
  test/lib/package_manager/yum_test.rb
Labels: Waiting on contributor

#759 Drop checkpoint segments check
  definitions/checks/foreman/check_checkpoint_segments.rb
  definitions/scenarios/upgrade_to_capsule_6_15.rb
  definitions/scenarios/upgrade_to_capsule_6_15_z.rb
  definitions/scenarios/upgrade_to_satellite_6_15.rb
  definitions/scenarios/upgrade_to_satellite_6_15_z.rb
Labels: Waiting on contributor

#761 Remove check for assets not coming from an RPM
  definitions/checks/original_assets.rb
Labels: Waiting on contributor

#748 Remove legacy code from installer feature
  definitions/features/installer.rb
  test/definitions/features/installer_test.rb
Labels: Waiting on contributor

#764 Release v1.2.12
  lib/foreman_maintain/version.rb
Labels: Waiting on contributor

#765 fix ruby tests badge
  README.md
Labels: Waiting on contributor

#767 drop katello pre 3.2.0 specialcase
  definitions/features/instance.rb
Labels: Waiting on contributor

#768 only add metadata once to the backup
  definitions/scenarios/backup.rb
Labels: Waiting on contributor

#769 drop apipie:cache call procedure
  definitions/procedures/foreman/apipie_cache.rb
Labels: Waiting on contributor

#770 drop remove docker procedure
  definitions/procedures/foreman_docker/remove_foreman_docker.rb
Labels: Waiting on contributor

#766 drop old and unused DB backup code
  definitions/checks/backup/directory_ready.rb
  definitions/scenarios/backup.rb
  lib/foreman_maintain/concerns/base_database.rb
Labels: Waiting on contributor, Not yet reviewed

#762 Check if CONFIG_FILE is defined
  lib/foreman_maintain/config.rb
Labels: Not yet reviewed
