Repository theforeman/foreman_maintain, pull requests merged in 2023-06, with the labels that each got.

#736 Fixes #36464 - always manage pulpcore services
  definitions/features/pulpcore.rb
Labels: Needs re-review, Waiting on contributor

#731 Default to INFO level logging
  lib/foreman_maintain.rb
  lib/foreman_maintain/config.rb
Labels: Waiting on contributor

#733 Use systemctl restart to restart services
  definitions/procedures/service/restart.rb
  lib/foreman_maintain/utils/service/systemd.rb
Labels: Needs re-review

#721 Fixes #33947 - only check directory permissions for backups with dumps
  definitions/checks/backup/directory_ready.rb
  definitions/scenarios/backup.rb
Labels: Waiting on contributor

#737 Release 1.3.2
  lib/foreman_maintain/version.rb
Labels: Waiting on contributor

#742 Release v1.2.10
  lib/foreman_maintain/version.rb
Labels: Waiting on contributor
